[package]
name = "static_map"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
rand ="0.8"
pi_null = "0.2"
pi_wy_rng="0.1"
fixedbitset="0.4"
